Formatted .format to f-string.
wecoach-ai/TTNet-Real-time-Analysis-System-for-Table-Tennis-Pytorch pull request #7
Opened 2024-08-05 12:36 UTC by Shreshtth

2024-08-05 13:27 UTC, onlinejudge95 commented on src/config/config.py
> +        configs.saved_weight_name = os.path.join(configs.checkpoints_dir, f'{configs.saved_fn}.pth')
We need to use `pathlib` APIs for managing OS paths here

2024-08-05 13:28 UTC, onlinejudge95 commented on src/data_process/ttnet_data_utils.py
> +                    img_path = os.path.join(images_dir, game_name, f'img_{sub_smooth_idx:06d}.jpg')
Same as above

2024-08-05 13:28 UTC, onlinejudge95 commented on src/data_process/ttnet_data_utils.py
> +                seg_path = os.path.join(annos_dir, game_name, 'segmentation_masks', f'{last_f_idx}.png')
Same as above

2024-08-05 13:28 UTC, onlinejudge95 commented on src/data_process/ttnet_dataset.py
> +    plt.savefig(os.path.join(out_images_dir, f'org_all_imgs_{example_index}.jpg'))
Same as above

2024-08-05 13:28 UTC, onlinejudge95 commented on src/data_process/ttnet_dataset.py
> +    plt.imsave(os.path.join(out_images_dir, f'augment_seg_img_{example_index}.jpg'), target_seg)
Same as above

2024-08-05 16:08 UTC, onlinejudge95 requested changes

2024-08-05 16:08 UTC, onlinejudge95 commented on src/data_process/ttnet_data_utils.py
>                  if not os.path.isfile(seg_path):
This needs to be migrated as well.

2024-08-05 16:08 UTC, onlinejudge95 commented on src/data_process/ttnet_video_loader.py
> +        assert os.path.isfile(video_path), f"No video at {video_path}"
This also needs to be migrated

2024-08-05 16:08 UTC, onlinejudge95 commented on src/data_process/ttnet_video_loader.py
>          os.makedirs(out_images_dir)
This needs to be migrated as well

2024-08-05 16:08 UTC, onlinejudge95 commented on src/demo.py
>              os.makedirs(configs.frame_dir)
This needs to be migrated as well

2024-08-05 16:08 UTC, onlinejudge95 commented on src/models/model_utils.py
> +    assert os.path.isfile(pretrained_path), f"=> no checkpoint found at '{pretrained_path}'"
This needs to be migrated as well

2024-08-05 16:08 UTC, onlinejudge95 commented on src/models/model_utils.py
> +    assert os.path.isfile(resume_path), f"=> no checkpoint found at '{resume_path}'"
This needs to be migrated as well

2024-08-05 16:08 UTC, onlinejudge95 commented on src/utils/init_paths.py
>              self.add_path(lib_path)
This can be merged in a single line

2024-08-05 16:08 UTC, onlinejudge95 commented on src/utils/logger.py
> +        logger_path = Path(logs_dir) / logger_fn
These can be compressed in a single line

2024-08-06 06:16 UTC, onlinejudge95 requested changes

2024-08-06 06:16 UTC, onlinejudge95 commented on src/data_process/ttnet_data_utils.py
> +                if not Path(seg_path).is_file():
`seg_path` is already a `Path` object.

I see a lot of occurrences for this, please fix all of them

2024-08-06 07:16 UTC, Shreshtth reviewed
@onlinejudge95 Please review these changes once.

2024-08-08 04:58 UTC, onlinejudge95 approved these changes

2024-08-08 04:59 UTC, merged